### ISSUE TITLE
gaz limit problem

### ISSUE THREAD

**Issue by diyquad** [second-state/how_to_deploy_uniswap#10]
Hi,
When try to deploy v2, their is an error.
I tryed to incread the gaz limit in deploy_uniswap_v2, as i saw a closed issue in the repo. (from 4700000 to 8000000) But doesn't change.
here is the error and new code

Maybe i didn't change the right place? Any idea how to make it work?

Thanks

```
Deploying Multicall now, please wait ...
0x481e3894ac8f062eaf4041d88664b6dc862780080b26565da9fc878598d2828d
Transaction hash: 0x481e3894ac8f062eaf4041d88664b6dc862780080b26565da9fc878598d2828d
(node:5155) UnhandledPromiseRejectionWarning: Error: The contract code couldn't be stored, please check your gas limit.
    at Object.TransactionError (/root/test/v2/uniswap-interface/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at Object.ContractCodeNotStoredError (/root/test/v2/uniswap-interface/node_modules/web3-core-helpers/lib/errors.js:95:21)
    at /root/test/v2/uniswap-interface/node_modules/web3-core-method/lib/index.js:335:49
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5155) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
(node:5155) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: The contract code couldn't be stored, please check your gas limit.
    at Object.TransactionError (/root/test/v2/uniswap-interface/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at Object.ContractCodeNotStoredError (/root/test/v2/uniswap-interface/node_modules/web3-core-helpers/lib/errors.js:95:21)
    at /root/test/v2/uniswap-interface/node_modules/web3-core-method/lib/index.js:335:49
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  receipt: {
    blockHash: '0x9b3d13e58ea23a1467bf0c07b8d21cb347febb086b87fd854b94f2de53b42592',
    blockNumber: 8627389,
    contractAddress: '0x5D0836E8721471C7329b2Ede2c385f1EF97E7E3a',
    cumulativeGasUsed: 4700000,
    from: '0x101447c86a76fc22330f332b0ed147eaa8edf597',
    gasUsed: 4700000,
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    status: false,
    to: null,
    transactionHash: '0x481e3894ac8f062eaf4041d88664b6dc862780080b26565da9fc878598d2828d',
    transactionIndex: 0,
    type: '0x0',
    events: {}
  }
}
```

deploy_uniswap_v2.js
```
// Uniswap V2 Multicall
    // V2 Multicall Deployment
    console.log("Deploying Multicall now, please wait ...");
    let uniswapMulticall;
    uniswapMulticall = await web3.eth.sendTransaction({
        from: accounts[2],
        data: uniswapMulticallBytecode
    }); // Charlie accounts[2] is the owner
    let uniswapMulticallInstance = new web3.eth.Contract(uniswapMulticallAbi, uniswapMulticall.contractAddress);
    uniswapMulticallInstance.deploy({
            data: uniswapMulticallBytecode
        })
        .send({
            from: accounts[2],
            gas: 8000000,
            gasPrice: '30000000000'
        }, function(error, transactionHash) {
            console.log(transactionHash);
        })
        .on('error', function(error) {
            console.log(error);
        })
        .on('transactionHash', function(transactionHash) {
            console.log("Transaction hash: " + transactionHash);
        })
        .on('receipt', function(receipt) {
            console.log("Contract address: " + receipt.contractAddress) // contains the new contract address
            data_object.contract_address.multicall = receipt.contractAddress;
            let data_to_write = JSON.stringify(data_object, null, 2);
            write_data(data_to_write);
        })
        .then(function(newContractInstance) {
            console.log(newContractInstance.options.address) // instance with the new contract address
        });
```

**Comment by diyquad** [comment]
solved by changing gaz price everywhere (not just in multicall)
