### ISSUE TITLE
Uniswap + Metamask + Binance Smart Chain

### ISSUE THREAD

**Issue by H1l4nd0r** [second-state/how_to_deploy_uniswap#5]
Tried to deploy and got this errors, what prices should I increase?

Name set to: Wrapped Ether
Deploying Multicall now, please wait ...
0x4b545c9dbbec85c34631bfabf6d574628318efc0242f05a8ca204792d4c905a2
Transaction hash: 0x4b545c9dbbec85c34631bfabf6d574628318efc0242f05a8ca204792d4c905a2
Deploying Migrator now, please wait ...
(node:30869) UnhandledPromiseRejectionWarning: Error: The contract code couldn't be stored, please check your gas limit.
    at Object.callback (/root/node_modules/web3-core-method/src/index.js:333:46)
    at sendTxCallback (/root/node_modules/web3-core-method/src/index.js:484:29)
    at /root/node_modules/web3-core-requestmanager/src/index.js:147:9
    at /root/node_modules/truffle-hdwallet-provider/dist/index.js:15:549917
    at /root/node_modules/truffle-hdwallet-provider/dist/index.js:1:140344
    at d (/root/node_modules/truffle-hdwallet-provider/dist/index.js:1:206203)
    at /root/node_modules/truffle-hdwallet-provider/dist/index.js:1:206256
    at t.default (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:564796)
    at /root/node_modules/truffle-hdwallet-provider/dist/index.js:1:206574
    at s (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:549761)
    at /root/node_modules/truffle-hdwallet-provider/dist/index.js:15:632708
    at t.i.onreadystatechange (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:748948)
    at t.e.dispatchEvent (/root/node_modules/truffle-hdwallet-provider/dist/index.js:1:142373)
    at t._setReadyState (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:753708)
    at t._onHttpResponseEnd (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:756793)
    at IncomingMessage.<anonymous> (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:756051)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:30869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30869) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: The contract code couldn't be stored, please check your gas limit.
    at Object.callback (/root/node_modules/web3-core-method/src/index.js:333:46)
    at sendTxCallback (/root/node_modules/web3-core-method/src/index.js:484:29)
    at /root/node_modules/web3-core-requestmanager/src/index.js:147:9
    at /root/node_modules/truffle-hdwallet-provider/dist/index.js:15:549917
    at /root/node_modules/truffle-hdwallet-provider/dist/index.js:1:140344
    at d (/root/node_modules/truffle-hdwallet-provider/dist/index.js:1:206203)
    at /root/node_modules/truffle-hdwallet-provider/dist/index.js:1:206256
    at t.default (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:564796)
    at /root/node_modules/truffle-hdwallet-provider/dist/index.js:1:206574
    at s (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:549761)
    at /root/node_modules/truffle-hdwallet-provider/dist/index.js:15:632708
    at t.i.onreadystatechange (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:748948)
    at t.e.dispatchEvent (/root/node_modules/truffle-hdwallet-provider/dist/index.js:1:142373)
    at t._setReadyState (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:753708)
    at t._onHttpResponseEnd (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:756793)
    at IncomingMessage.<anonymous> (/root/node_modules/truffle-hdwallet-provider/dist/index.js:15:756051)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
0xcabf4a9efd495c30006a7bab274edae212d75fde87d22aaf7430fce4b4baa33b
Transaction hash: 0xcabf4a9efd495c30006a7bab274edae212d75fde87d22aaf7430fce4b4baa33b
Contract address: 0x6c0EdD87dd4bb0b9f416A1bD6Fa90d4900255B71
0x6c0EdD87dd4bb0b9f416A1bD6Fa90d4900255B71
Data written to file
(node:30869) UnhandledPromiseRejectionWarning: Error: invalid address (arg="_router", coderType="address", value="")
    at Object.throwError (/root/node_modules/ethers/utils/errors.js:68:17)
    at CoderAddress.encode (/root/node_modules/ethers/utils/abi-coder.js:467:20)
    at /root/node_modules/ethers/utils/abi-coder.js:605:59
    at Array.forEach (<anonymous>)
    at pack (/root/node_modules/ethers/utils/abi-coder.js:604:12)
    at CoderTuple.encode (/root/node_modules/ethers/utils/abi-coder.js:764:16)
    at AbiCoder.encode (/root/node_modules/ethers/utils/abi-coder.js:897:77)
    at ABICoder.encodeParameters (/root/node_modules/web3-eth-abi/src/index.js:96:27)
    at /root/node_modules/web3-eth-contract/src/index.js:426:24
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/root/node_modules/web3-eth-contract/src/index.js:425:12)
    at Object._processExecuteArguments (/root/node_modules/web3-eth-contract/src/index.js:741:39)
    at Object._executeMethod (/root/node_modules/web3-eth-contract/src/index.js:766:54)
    at /root/uniswap-interface/how_to_deploy_uniswap/uniswap_v2/deploy_uniswap_v2.js:251:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:30869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by H1l4nd0r** [comment]
will try to add some gas
