### ISSUE TITLE
Getting invalid address

### ISSUE THREAD

**Issue by Yudiz-Blockchain** [second-state/how_to_deploy_uniswap#7]
`Data written to file
(node:5761) UnhandledPromiseRejectionWarning: Error: invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.0.10) (argument="_factoryV1", value="", code=INVALID_ARGUMENT, version=abi/5.0.7)
    at Logger.makeError (/Users/yudiz/Documents/Practise/uniswap/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/Users/yudiz/Documents/Practise/uniswap/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at Logger.throwArgumentError (/Users/yudiz/Documents/Practise/uniswap/node_modules/@ethersproject/logger/lib/index.js:191:21)
    at AddressCoder.Coder._throwError (/Users/yudiz/Documents/Practise/uniswap/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:40:16)
    at AddressCoder.encode (/Users/yudiz/Documents/Practise/uniswap/node_modules/@ethersproject/abi/lib/coders/address.js:29:18)
    at /Users/yudiz/Documents/Practise/uniswap/node_modules/@ethersproject/abi/lib/coders/array.js:71:19
    at Array.forEach (<anonymous>)
    at Object.pack (/Users/yudiz/Documents/Practise/uniswap/node_modules/@ethersproject/abi/lib/coders/array.js:57:12)
    at TupleCoder.encode (/Users/yudiz/Documents/Practise/uniswap/node_modules/@ethersproject/abi/lib/coders/tuple.js:36:24)
    at AbiCoder.encode (/Users/yudiz/Documents/Practise/uniswap/node_modules/@ethersproject/abi/lib/abi-coder.js:86:15)
    at ABICoder.encodeParameters (/Users/yudiz/Documents/Practise/uniswap/node_modules/web3-eth-abi/lib/index.js:121:27)
    at /Users/yudiz/Documents/Practise/uniswap/node_modules/web3-eth-contract/lib/index.js:439:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/Users/yudiz/Documents/Practise/uniswap/node_modules/web3-eth-contract/lib/index.js:438:8)
    at Object._processExecuteArguments (/Users/yudiz/Documents/Practise/uniswap/node_modules/web3-eth-contract/lib/index.js:701:39)
    at Object._executeMethod (/Users/yudiz/Documents/Practise/uniswap/node_modules/web3-eth-contract/lib/index.js:720:68)
    at /Users/yudiz/Documents/Practise/uniswap/uniswap-interface/how_to_deploy_uniswap/uniswap_v2/deploy_uniswap_v2.js:251:10
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:5761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 78)
(node:5761) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Any solution? Deploying v2
![Screenshot 2021-02-26 at 5 53 42 PM](https://user-images.githubusercontent.com/70308073/109299737-97dafb80-785b-11eb-9406-dce7982fd611.png)

**Comment by tpmccallum** [comment]
It looks like the script is looking for the Uniswap V1 contract address on whichever network you are running on. 
Do you have Uniswap V1 Factory deployed on that network, and is the Uniswap V1 Factory contract address listed in your installation_data.json file?
https://github.com/second-state/how_to_deploy_uniswap/blob/master/installation_data.json#L13

**Comment by yossigruner** [comment]
@Yudiz-Blockchain you must deploy the V1 first, I had the same problem

**Comment by Yudiz-Blockchain** [comment]
Thank You! @yossigruner & @tpmccallum
